### ISSUE TITLE
Uninitialised variable in Heliostat_AzElAod.cpp

### ISSUE THREAD

**Issue by bje-** [NREL/ssc#105] opened 2017-12-18 08:24 UTC
Found by clang:

    ../tcs/Heliostat_AzElAod.cpp:181:18: error: variable 'rows' is uninitialized when used here [-Werror,-Wuninitialized]
                    for(int i=0; i<rows; i++){
                                   ^~~~

Indeed, if you inspect the code, `rows` is uninitialised.

**Comment by nickdiorio** [comment] 2018-01-05 23:18
This was caused by an erroneous commenting to remove a warning in: 3525cb2e4352d398a04cc7fbcf9e13ab1d46bb9d

**Comment by nickdiorio** [comment] 2018-01-05 23:20
I've fixed in e6aab1344df217f22b1e15beb0c8b455a168fd5e

**Closed by nickdiorio** 2018-01-05 23:20 UTC
