### ISSUE TITLE
Module modeled loss is positive

### ISSUE THREAD

**Issue by nickdiorio** [NREL/ssc#197] opened 2018-10-08 19:30 UTC
**Describe the bug**
There are certain instances I've seen where the reported module loss is positive.
[Baseline-series6.zip](https://github.com/NREL/ssc/files/2457429/Baseline-series6.zip)

**To Reproduce**
1. Open the attached .sam file in the develop branch of ssc and SAM
2. Click on the case "Case C.."
3. Run the simulation
4. Observe a +0.85% gain in the module loss

**Expected behavior**
A negative module loss

**Screenshots**
![image](https://user-images.githubusercontent.com/5658281/46629477-32590980-cafe-11e8-8fce-426cc8594e6f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Develop branch head of ssc and sam repositories

**Comment by janinefreeman** [comment] 2018-10-08 22:02
Does this happen in the current release also?

**Comment by nickdiorio** [comment] 2018-10-15 23:15
This appears to be be due to the way the module model loss is calculated, which is:

'loss' = `annual_dc_nominal - annual_dc_gross - annual_snow_loss - annual_mppt_voltage_clipping' / annual_dc_nominal`.  

Issues:
1. I believe this equation should remove `annual_mppt_voltage_clipping`, as it is already accounted for in `annual_dc_gross`.
2. `annual_dc_nominal` is calculated by multiplying the nominal plane-of-array irradiance by the nominal module efficiency and area.  Within the calculation of `annual_dc_gross`, there are time steps where the module efficiency exceeds the nominal efficiency due to the air mass modifier.  This implies that the air-mass modifier can provide a boost to the overall irradiance, or that the air-mass modifier is incorrectly applied.

There are several potential problems here which should be addressed.  The most robust way would be to investigate why the air mass modifier is boosting the efficiency.  Then, for clearer communication, these we should break the module losses into several components so they can be more clearly communicated.

- incidence angle loss (completed)
- air mass (or spectral?)
- temperature
- any others?

**Comment by nickdiorio** [comment] 2018-10-15 23:17
Note, in case it wasn't clear, the reason the loss is positive is because `annual_dc_gross` exceeds `annual_dc_nominal`.

**Comment by mikofski** [comment] 2018-10-16 02:58
I believe it is correct for the instantaneous module efficiency to increase above the nominal value at times when the spectral mismatch is greater than one.

>This implies that the air-mass modifier can provide a boost to the overall irradiance, or that the air-mass modifier is incorrectly applied.

I believe a more correct interpretation is that there are times when the incident solar spectrum matches the quantum efficiency and improves the module efficiency. It's not that there's more light. It's that there's more of the color light that the module can convert to electrons.

**Comment by jdnewmil** [comment] 2018-10-16 06:19
There are multiple ways for deviations from STC nominal performance to yield improved performance. Very cold temperatures, modules with high series resistance that implies reduced performance at STC but operated at low irradiance, spectral "match"... it is even possible for IAM to exceed 1.0 by very small amounts on textured glass. That said, I have not investigated this particular report so cannot comment on its merits.

**Comment by nickdiorio** [comment] 2018-10-16 13:52
@mikofski , @jdnewmil , thanks for your quick insights, that's very helpful.  I'm going to investigate today to confirm that we are applying air-mass modifications correctly.  I'll compare how PVLIB is applying them and verify that we are doing a similar treatment.

Currently our procedure in the CEC 6-parameter module model is to derate the effective plane-of-array irradiance by the air-mass modifier in the following way:

![image](https://user-images.githubusercontent.com/5658281/47021306-680e7b80-d118-11e8-8845-7a91d68bb8c8.png)

Where:
![image](https://user-images.githubusercontent.com/5658281/47021328-7492d400-d118-11e8-93d3-52d6797692a2.png)

**Comment by cwhanse** [comment] 2018-10-16 14:04
@nickdiorio Agree with @jdnewmil @Mikofski here.  I think the error, if there is one, is calling the spectral modifier a loss.  It is not like soiling or reflections which by definition only reduce irradiance reaching the cells.  The spectral modifier (I don't like the 'mismatch' adjective here but it is customary) scales the photocurrent relative to AM 1.5.  Photocurrent can increase or decrease as spectrum changes, as @mikofski says.

**Comment by nickdiorio** [comment] 2018-10-16 14:09
Thanks @cwhanse , that's a good point.  I'll do some testing and comparison with PVLIB and see if we can more clearly communicate that this is a modifier relative to AM 1.5, not necessarily a loss.

**Comment by janinefreeman** [comment] 2018-10-16 14:18
I agree with @mikofski that instantaneous module efficiency can be greater than nominal efficiency, and the same thing for spectral modifier. However, given that the value in the graph is an annual loss term, I consider it highly unlikely for it to actually be a negative loss throughout a whole year. I would guess this is a bug. However, I would not be surprised if it's only a bug in the way that annual loss is calculated, and not in the actual way the models themselves are applied in SAM, since the calculations for those loss diagrams (the line of code @nickdiorio identified as being a problem) are not particularly robust.

**Comment by mikofski** [comment] 2018-10-17 00:46
@nickdiorio Thanks for identifying this issue and for doing the work to take a deeper look into it's cause.

I think it would be very interesting to see the daytime values of the 8760 calculated for airmass and for the "spectral modifier" `f1`. Figure 6 in the [Sandia PV Array Performance Model](https://prod.sandia.gov/techlib-noauth/access-control.cgi/2004/043535.pdf) shows that for Si modules, this peaks at 1.05 at about 3.5 atmospheres, but for thin-film it's the opposite, `f1` peaks at 1.025 at 1-atmosphere and decreases as airmass increases.
![image](https://user-images.githubusercontent.com/1385621/47054497-f578bc80-d166-11e8-8206-6b338ef08e16.png)

Another thing that might be interesting is to check that the coefficients of the 4th order polynomial `f1` are stable in the expected range of airmasses, say from 0.5 to 6.5 atmospheres. For example, if I plot a Si and a CdTe module from the SAM database, I get these curves, which look like the ones from SAPM Fig 6.
![airmass-polynomial](https://user-images.githubusercontent.com/1385621/47055265-5aceac80-d16b-11e8-9f19-7fe140ff5ce6.png)

**Comment by janinefreeman** [comment] 2018-10-24 20:59
Update: 
1. [unrelated] the original SAM file built in Beta version 2018.9.13 didn't successfully update to current release branch (a separate bug to investigate). I checked out SSC and SAM 2018.9.13 Beta tags on my machine and was able to run the file.
2. Further investigation yields several things contributing to the positive value for module modeled loss:
    i. Kansas City MO (the weather file used in this case) has temp/irradiance values that correspond to very low module temperature losses
    ii. Module cover losses used to be a decent chunk of the module modeled loss, but since they are now broken out separately, module modeled losses are lower all around
    iii. [the part that I think is a bug] There may be a bug in the "CEC performance model with user entered specifications" model. I get a ~0.7% difference in annual energy when the ONLY difference between two cases is the 'module_model' flag. Confirmed creating SDKtool scripts for both cases and comparing the two files (see attached LK scripts). The user-entered model reports higher output, probably contributing to the positive module modeled losses seen in the SAM file. This possible bug was also present in the 2017.9.5 release of SAM (example file confirming this attached). I have not investigated the cause of these differences yet, that's next on my list!
[Bug update.zip](https://github.com/NREL/ssc/files/2512315/Bug.update.zip)

**Comment by mikofski** [comment] 2018-10-26 03:31
Since we're on the topic, SAM should really adopt the FirstSolar spectral correction that also uses precipitable water, but of course that should be it's own separate issue 😉

**Comment by cwhanse** [comment] 2018-10-26 14:20
@dguittet @mikofski for spectral response measurements, there are concepts of external and internal quantum efficiency - these are different quantities. As I understand it, external quantum efficiency is basically power / plane of array irradiance, whereas internal efficiency is power / irradiance reaching the cells.  Both quantities are informative.  I think it the important aspect is that SAM is clear which irradiance is being used to calculate efficiency.

**Comment by janinefreeman** [comment] 2018-10-26 14:50
Also, @dguittet demonstrated to me that I was comparing the wrong variables when I identified a possible bug above- I forgot that there are separate, co-existing input variables for the CEC database option versus the user-entered 6-parameter option in the LK scripts created by SAM that you have to match up between the two models. Fixed SAM file with the two cases matching within the bounds of UI rounding errors attached here. Thanks Darice! 
[fixed.zip](https://github.com/NREL/ssc/files/2519675/fixed.zip)

**Comment by dguittet** [comment] 2018-10-31 19:32
@mikofski @janinefreeman Yes there are definitely improvements to the module model we'd like to get to! Thanks @cwhanse for the explanation.

Here are some plots showing the module efficiency versus ambient temperature and nominal poa after module cover loss (the plot with cell temperature and poa after module cover looked very similar). The gray points are where the module efficiency is less than the nominal efficiency of 15.9%.

![eff_vs_ambtmp_poanominal_plot](https://user-images.githubusercontent.com/29387736/47812903-292f1700-dd0f-11e8-82a9-b085f4fb41a3.png)

We do not have any measured data in that region, since we do have [data](https://ieeexplore.ieee.org/document/6925171) for 2 CdTe modules but they do not have many points in that region. In the plot below, all the points have less than nominal efficiency.

![measuredmodule__eff_vs_ambtmp_poanominal_plot](https://user-images.githubusercontent.com/29387736/47812936-45cb4f00-dd0f-11e8-8c6a-4db68931f7e6.png)

What we do know from analysis of that data is that for the 6 parameter single diode model as implemented in SAM, large errors are mostly correlated with low irradiance levels.

![6parerrorbycondition_cdte](https://user-images.githubusercontent.com/29387736/47813133-bbcfb600-dd0f-11e8-82ca-2dfbb245a7b9.png)

**Comment by cwhanse** [comment] 2018-10-31 20:44
@dguittet I'm having a bit of trouble with the figures you just posted.  Are you saying that the modeled efficiency is greater than the observed efficiency at low irradiance?  Also, are the coefficients for the 6par model taken from the SAM (CEC) database, or were they developed specifically for the CdTe modules in that mPert dataset?

**Comment by dguittet** [comment] 2018-11-01 18:31
@cwhanse In the first plot, the colored points show where the modeled efficiency is greater than the nominal efficiency for the module in the .sam project. I believe these coefficients are not from the database. Perhaps @nickdiorio can say more on what module they describe.

The second and third plots are using the measured modules from the linked dataset. The first one shows that there are no points where the modeled efficiency exceeded the nominal. Here's a better-labeled version of the third plot. And yes it does show that the modeled efficiency tended to be higher than measured efficiency at low irradiance and temp, at least for those 2.

![6parerrorbycondition_cdte](https://user-images.githubusercontent.com/29387736/47871373-8b505080-ddd1-11e8-8bcf-ad77cebb536b.png)

All this was to say, I don't have enough knowledge to say whether or not this behavior is expected.

**Comment by janinefreeman** [comment] 2018-11-08 18:35
The detailed discussion here has convinced @nickdiorio and I that as @cwhanse points out, this is not a bug, but actually an error in describing the phenomenon as a loss. We plan to break out various sources of module losses/gains in next year's release, so I'm going to close this issue and reference the great discussion here in the new issue I create for why we need to break out module performance losses separately. :)

**Closed by janinefreeman** 2018-11-08 18:35 UTC
Labels: bug
